### PR TITLE
Go to the web UI

### PR DESCRIPTION
**Pull request by stephdl**
Create a panel to manage virtualhost inside the User Interface

### CODE REVIEW

**Comment by stephdl** [comment]
sftpgo admin password : admin:admin

when you create a vhost, the sftpgo user password is the FpmPort (eg: 9001:9001)

**Comment by stephdl** [comment]
image

image
image
image
image

**Comment by stephdl** [comment]
status page
image

**Comment by stephdl** [comment]
settiings page
image
image
image

**Comment by stephdl** [comment]
about page

image

**Review by andre8244 — APPROVED** [review]

**Review by andre8244 — APPROVED** [review]
UI changes are ok

**Pull request merged**
